//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by D:\git\TortoiseSI\src\Resources\TortoiseProcENG.rc
//
#define IDR_MAINFRAME                   1
#define IDI_COMMIT                      123
#define IDI_REVERT                      125
#define IDD_ABOUT                       129
#define IDI_DIFF                        135
#define IDR_ANIMATION                   148
#define IDR_MOVEANI                     149
#define IDR_SEARCH                      163
#define IDI_DRIVES                      164
#define IDI_SSH                         165
#define IDI_PROXY                       166
#define IDI_MISC                        167
#define IDB_LOGOFLIPPED                 168
#define IDB_TTF_BMP                     169
#define IDI_SET_OVERLAYS                190
#define IDI_GENERAL                     195
#define IDI_LOOKANDFEEL                 196
#define IDI_ICONSET                     197
#define IDI_DIALOGS                     198
#define IDR_HTML_CLONEDLG               200
#define IDB_CANCELHIGHLIGHT             201
#define IDB_BITMAP1                     203
#define IDI_WARNING_GENERAL             210
#define IDR_CLEANUPANI                  212
#define IDI_ACTIONADDED                 213
#define IDI_ACTIONDELETED               214
#define IDI_ACTIONMODIFIED              215
#define IDI_ACTIONREPLACED              216
#define IDI_SAVEDDATA                   225
#define IDI_GRAPHBAR                    229
#define IDI_GRAPHBARSTACKED             230
#define IDI_GRAPHLINE                   231
#define IDI_GRAPHLINESTACKED            232
#define IDI_GRAPHPIE                    233
#define IDI_SWITCHLEFTRIGHT             234
#define IDR_STATGRAPH                   235
#define IDI_HOOK                        237
#define IDI_REPOBROWSER_BKG             244
#define IDC_PANCUR                      250
#define IDC_PANCURDOWN                  251
#define IDI_TORTOISEBLAME               252
#define IDR_ACC_LOGDLG                  254
#define IDI_ADD_BKG                     255
#define IDI_RESOLVE_BKG                 256
#define IDI_REVERT_BKG                  257
#define IDI_COMMIT_BKG                  258
#define IDI_CFM_BKG                     260
#define IDR_DOWNLOAD                    263
#define IDI_CANCELNORMAL                264
#define IDI_CANCELPRESSED               265
#define IDI_LOGFILTER                   266
#define IDI_FILTEREDIT                  267
#define IDI_COPY_BKG                    270
#define IDI_EXPORT_BKG                  271
#define IDI_IMPORT_BKG                  272
#define IDI_MERGE_BKG                   273
#define IDI_RENAME_BKG                  274
#define IDI_SWITCH_BKG                  275
#define IDI_BUGTRAQ                     284
#define IDI_UP                          286
#define IDI_MKDIR                       289
#define IDI_REFRESH                     290
#define IDI_SAVE                        291
#define IDI_SAVEAS                      292
#define IDI_EXPLORER                    293
#define IDI_OPEN                        294
#define IDI_UPDATE_BKG                  295
#define IDB_GIT                         299
#define IDI_GITCONFIG                   319
#define IDI_GITREMOTE                   320
#define IDR_ACC_COMMITDLG               325
#define IDI_SHOWBRANCHES                326
#define IDI_ACTIONFETCHING              332
#define IDB_BITMAP2                     336
#define IDB_BITMAP_REFTYPE              336
#define IDI_IMPORTPATHCES_BKG           337
#define IDI_LIBRARY                     339
#define IDI_RESTORE                     341
#define IDI_RESTOREOVL                  342
#define IDI_JUMPUP                      343
#define IDI_JUMPDOWN                    344
#define IDI_GITCREDENTIAL               346
#define IDI_EXTERNALOVL                 347
#define IDI_MERGEACTIVE                 348
#define IDI_EXECUTABLEOVL               349
#define IDI_SYMLINKOVL                  350
#define IDI_SPELL                       351
#define IDI_FILE                        352
#define IDI_CODE                        353
#define IDI_SNIPPET                     354
#define IDI_CERTCHECK                   355
#define IDI_TORTOISEUDIFF               356
#define IDS_APPNAME                     1026
#define IDC_UPDATE                      1031
#define IDC_VERSIONABOUT                1054
#define IDC_VERSIONBOX                  1075
#define IDC_WEBLINK                     1084
#define IDC_SUPPORTLINK                 1085
#define IDC_SUBMIT_TO_CP_LABEL          1832
#define IDC_CREATE_CP_BUTTON            1833
#define IDC_SUBMIT_CP_BUTTON            1834
#define IDR_REVGRAPHBAR                 4581
#define IDR_REVGRAPHGLYPHS              4582
#define ID_REVGRAPH_ZOOMCOMBO           4583
#define IDD_SICOMMITDLG                 4596
#define ID_VIEW_ZOOMIN                  32772
#define ID_VIEW_ZOOMOUT                 32773
#define ID_VIEW_ZOOM100                 32803
#define ID_VIEW_ZOOMALL                 32804
#define ID_FILE_SAVEGRAPHAS32805        32805
#define ID_FILE_SAVESTATGRAPHAS         32806
#define ID_FILTER_EXCLUDEPATHS          32807
#define ID_FILTER_EXCLUDEREVISIONS      32808
#define ID_VIEW_ZOOMHEIGHT              32809
#define ID_VIEW_ZOOMWIDTH               32810
#define ID_VIEW_GROUPBRANCHES           32811
#define ID_VIEW_TOPALIGNTREES           32812
#define ID_VIEW_SHOWOVERVIEW            32813
#define ID_VIEW_TOPDOWN                 32814
#define ID_URL_FOCUS                    32814
#define IDC_SUBMIT_CP_COMBOBOX          32814
#define ID_VIEW_SHOWHEAD                32815
#define ID_VIEW_SHOWDIFFPATHS           32816
#define ID_VIEW_SHOWALLREVISIONS        32817
#define ID_VIEW_EXACTCOPYSOURCE         32818
#define ID_VIEW_FOLDTAGS                32819
#define ID_VIEW_REMOVEDELETEDONES       32820
#define ID_LOGDLG_REFRESH               32821
#define ID_LOGDLG_FIND                  32822
#define ID_VIEW_REMOVEUNCHANGEDBRANCHES 32823
#define ID_VIEW_REMOVETAGS              32824
#define ID_LOGDLG_FOCUSFILTER           32825
#define ID_VIEW_SHOWWCREV               32826
#define ID_FOCUS_MESSAGE                32837
#define ID_VIEW_SHOWWCMODIFICATION      32838
#define ID_VIEW_FILTER                  32839
#define ID_VIEW_SHOWTREESTRIPES         32840
#define ID_FILE_SAVEGRAPHAS             32841
#define ID_MENUEXIT                     32842
#define ID_MENUHELP                     32843
#define ID_VIEW_COMPAREREVISIONS        32844
#define ID_VIEW_COMPAREHEADREVISIONS    32845
#define ID_VIEW_UNIFIEDDIFF             32846
#define ID_VIEW_UNIFIEDDIFFOFHEADREVISIONS 32847
#define IDI_REVGRAPHBAR                 32850
#define ID_FOCUS_FILELIST               32857
#define ID_GO_FORWARD                   32867
#define ID_GO_BACKWARD                  32868
#define ID_GO_UP                        32869
#define ID_GO_DOWN                      32870
#define ID_GO_BACKWARD_SELECT           32871
#define ID_GO_FORWARD_SELECT            32872
#define ID_SELECT_SEARCHFIELD           32873
#define IDR_ACC_SICOMMITDLG             32876

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        361
#define _APS_NEXT_COMMAND_VALUE         32878
#define _APS_NEXT_CONTROL_VALUE         1835
#define _APS_NEXT_SYMED_VALUE           201
#endif
#endif
